language: python
install: pip install tox
matrix:
  include:
    - python: 2.7
      env: TOX_ENV=py26
    - python: 2.7
      env: TOX_ENV=py27
    - python: 2.7
      env: TOX_ENV=py33
    - python: 2.7
      env: TOX_ENV=py34
    - python: 2.7
      env: TOX_ENV=pypy
    - python: 2.7
      env: TOX_ENV=flake8
    - python: 3.5
      env: TOX_ENV=py35
    - python: 3.6-dev
      env: TOX_ENV=py36
script: 
  - tox -e $TOX_ENV
